server.port: 9099

spring:
  application:
    name: spring-boot-local
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=test
    username: postgres
    password: postgres
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      idle-timeout: 60000
      pool-name: DataHikariCP
      max-lifetime: 840000
      connection-timeout: 50000
      connection-test-query: select 1
  jpa:
    properties:
      hibernate.jdbc.time_zone: Asia/Singapore # critical as we use LocalDateTime
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: none
    open-in-view: false
logging:
  level:
    root: INFO
  file:
    name: logs/local.log
    max-size: 10MB
    max-history: 10
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"